name: 'Merge branch'
description: 'A GitHub Action that merge PR branch to other branchs'
author: Miguel Savignano
inputs:
  type:
    type: 'labeled | now'
    required: false
    default: 'labeled'
  label_name:
    description: 'PR Label name'
    required: false
  target_branch:
    description: 'The name of target branch to merge'
    required: true
  from_branch:
    description: 'Alias head_to_merge input'
    required: false
  head_to_merge:
    description: 'The branch name or hash to merge. default GITHUB_SHA'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'git-merge'
  color: 'purple'
